package net.plat12.kaantaa;

import java.util.List;
import java.util.Map;

import static net.plat12.kaantaa.Util.normalize;

public class LanguageCodes {

    private static final Map<String, String> VALUES = Map.<String, String>ofEntries(
            Map.entry("(Afrikaans) Afrikaans (Suid-Afrika)", "af_za"),
            Map.entry("(Arabic) العربية (العالم العربي)", "ar_sa"),
            Map.entry("(Asturian) Asturianu (Asturies)", "ast_es"),
            Map.entry("(Azerbaijani) Azərbaycanca (Azərbaycan)", "az_az"),
            Map.entry("(Bashkir) Башҡортса (Башҡортостан, Рәсәй)", "ba_ru"),
            Map.entry("(Bavarian) Boarisch (Bayern)", "bar"),
            Map.entry("(Belarusian, Cyrillic) Беларуская (Беларусь)", "be_by"),
            Map.entry("(Belarusian, Latin) Biełaruskaja (Biełaruś)", "be_latn"),
            Map.entry("(Bulgarian) Български (България)", "bg_bg"),
            Map.entry("(Breton) Brezhoneg (Breizh)", "br_fr"),
            Map.entry("(Brabantian) Braobans (Braobant)", "brb"),
            Map.entry("(Bosnian) Bosanski (Bosna i Hercegovina)", "bs_ba"),
            Map.entry("(Catalan) Català (Catalunya)", "ca_es"),
            Map.entry("(Chuvash) Чӑвашла (Чӑваш Ен, Раҫҫей)", "cv_cu"),
            Map.entry("(Czech) Čeština (Česko)", "cs_cz"),
            Map.entry("(Welsh) Cymraeg (Cymru)", "cy_gb"),
            Map.entry("(Danish) Dansk (Danmark)", "da_dk"),
            Map.entry("(Austrian German) Deitsch (Österreich)", "de_at"),
            Map.entry("(Swiss German) Schwiizerdutsch (Schwiiz)", "de_ch"),
            Map.entry("(German) Deutsch (Deutschland)", "de_de"),
            Map.entry("(Greek) Ελληνικά (Ελλάδα)", "el_gr"),
            Map.entry("(Australian English) English (Australia)", "en_au"),
            Map.entry("(Canadian English) English (Canada)", "en_ca"),
            Map.entry("(British English) English (United Kingdom)", "en_gb"),
            Map.entry("(New Zealand English) English (New Zealand)", "en_nz"),
            Map.entry("(Pirate English) Pirate Speak (The Seven Seas)", "en_pt"),
            Map.entry("(Upside Down British English) ɥsᴉꞁᵷuƎ (uʍoᗡ ǝpᴉsd∩)", "en_ud"),
            Map.entry("(American English) English (US)", "en_us"),
            Map.entry("(Anglish, English minus borrowed words) Anglish (Oned Riches)", "enp"),
            Map.entry("(Shakespearean/Early Modern English) Shakespearean English (Kingdom of England)", "enws"),
            Map.entry("(Esperanto) Esperanto (Esperantujo)", "eo_uy"),
            Map.entry("(Argentinian Spanish) Español (Argentina)", "es_ar"),
            Map.entry("(Chilean Spanish) Español (Chile)", "es_cl"),
            Map.entry("(Ecuadorian Spanish) Español (Ecuador)", "es_ec"),
            Map.entry("(European Spanish) Español (España)", "es_es"),
            Map.entry("(Mexican Spanish) Español (México)", "es_mx"),
            Map.entry("(Uruguayan Spanish) Español (Uruguay)", "es_uy"),
            Map.entry("(Venezuelan Spanish) Español (Venezuela)", "es_ve"),
            Map.entry("(Andalusian) Andalûh (Andaluçía)", "esan"),
            Map.entry("(Estonian) Eesti keel (Eesti)", "et_ee"),
            Map.entry("(Basque) Euskara (Euskal Herria)", "eu_es"),
            Map.entry("(Persian) فارسی (ایران)", "fa_ir"),
            Map.entry("(Finnish) Suomi (Suomi)", "fi_fi"),
            Map.entry("(Filipino) Filipino (Pilipinas)", "fil_ph"),
            Map.entry("(Faroese) Føroyskt (Føroyar)", "fo_fo"),
            Map.entry("(Canadian French) Français (Canada)", "fr_ca"),
            Map.entry("(Swiss French) Français (Suisse)", "fr_ch"),
            Map.entry("(European French) Français (France)", "fr_fr"),
            Map.entry("(East Franconian) Fränggisch (Franggn)", "fra_de"),
            Map.entry("(Friulian) Furlan (Friûl)", "fur_it"),
            Map.entry("(Frisian) Frysk (Fryslân)", "fy_nl"),
            Map.entry("(Irish) Gaeilge (Éire)", "ga_ie"),
            Map.entry("(Scottish Gaelic) Gàidhlig (Alba)", "gd_gb"),
            Map.entry("(Galician) Galego (Galicia / Galiza)", "gl_es"),
            Map.entry("(Gallo) Galo (Bertègn)", "go_fr"),
            Map.entry("(Gothic) 𐌲𐌿𐍄𐍂𐌰𐌶𐌳𐌰 (𐌸𐍉 𐌰𐌹𐌽𐌰𐌼𐌿𐌽𐌳𐍉𐌽𐌰 𐍂𐌴𐌹𐌺𐌾𐌰)", "got_de"),
            Map.entry("(Halychian) Галицка (Галичина, Вкраїна)", "hal_ua"),
            Map.entry("(Hawaiian) 'Ōlelo Hawai'i (Hawai'i)", "haw_us"),
            Map.entry("(Hebrew) עברית (ישראל)", "he_il"),
            Map.entry("(Hindi) हिंदी (भारत)", "hi_in"),
            Map.entry("(High Norwegian) Høgnorsk (Norig)", "hn_no"),
            Map.entry("(Croatian) Hrvatski (Hrvatska)", "hr_hr"),
            Map.entry("(Hungarian) Magyar (Magyarország)", "hu_hu"),
            Map.entry("(Armenian) Հայերեն (Հայաստան)", "hy_am"),
            Map.entry("(Indonesian) Bahasa Indonesia (Indonesia)", "id_id"),
            Map.entry("(Igbo) Igbo (Naigeria)", "ig_ng"),
            Map.entry("(Ido) Ido (Idia)", "io_en"),
            Map.entry("(Icelandic) Íslenska (Ísland)", "is_is"),
            Map.entry("(Interslavic) Medžuslovjansky (Slovjanščina)", "isv"),
            Map.entry("(Italian) Italiano (Italia)", "it_it"),
            Map.entry("(Japanese) 日本語 (日本)", "ja_jp"),
            Map.entry("(Lojban) la .lojban. (la jbogu'e)", "jbo_en"),
            Map.entry("(Georgian) ქართული (საქართველო)", "ka_ge"),
            Map.entry("(Kazakh) Қазақша (Қазақстан)", "kk_kz"),
            Map.entry("(Kannada) ಕನ್ನಡ (ಭಾರತ)", "kn_in"),
            Map.entry("(Korean) 한국어 (대한민국)", "ko_kr"),
            Map.entry("(Kölsch/Ripuarian) Kölsch/Ripoarisch (Rhingland)", "ksh"),
            Map.entry("(Cornish) Kernewek (Kernow)", "kw_gb"),
            Map.entry("(Kyrgyz) Кыргызча (Кыргызстан)", "ky_kg"),
            Map.entry("(Latin) Latina (Latium)", "la_la"),
            Map.entry("(Luxembourgish) Lëtzebuergesch (Lëtzebuerg)", "lb_lu"),
            Map.entry("(Limburgish) Limburgs (Limburg)", "li_li"),
            Map.entry("(Lombard) Lombard (Lombardia)", "lmo"),
            Map.entry("(Lao) ລາວ (ປະເທດລາວ)", "lo_la"),
            Map.entry("(LOLCAT) LOLCAT (Kingdom of Cats)", "lol_us"),
            Map.entry("(Lithuanian) Lietuvių (Lietuva)", "lt_lt"),
            Map.entry("(Latvian) Latviešu (Latvija)", "lv_lv"),
            Map.entry("(Literary Chinese) 文言 (華夏)", "lzh"),
            Map.entry("(Macedonian) Македонски (Северна Македонија)", "mk_mk"),
            Map.entry("(Mongolian) Монгол (Монгол Улс)", "mn_mn"),
            Map.entry("(Malay) Bahasa Melayu (Malaysia)", "ms_my"),
            Map.entry("(Maltese) Malti (Malta)", "mt_mt"),
            Map.entry("(Nahuatl) Mēxikatlahtōlli (Mēxiko)", "nah"),
            Map.entry("(Low German) Plattdüütsh (Düütschland)", "nds_de"),
            Map.entry("(Dutch, Flemish) Vlaams (België)", "nl_be"),
            Map.entry("(Dutch) Nederlands (Nederland)", "nl_nl"),
            Map.entry("(Norwegian Nynorsk) Norsk nynorsk (Noreg)", "nn_no"),
            Map.entry("(Norwegian Bokmål) Norsk bokmål (Norge)", "no_no"),
            Map.entry("(Occitan) Occitan (Occitània)", "oc_fr"),
            Map.entry("(Elfdalian) Övdalska (Swerre)", "ovd"),
            Map.entry("(Polish) Polski (Polska)", "pl_pl"),
            Map.entry("(Popoloca) Ngiiwa (Ndanìꞌngà)", "pls"),
            Map.entry("(Brazilian Portuguese) Português (Brasil)", "pt_br"),
            Map.entry("(European Portuguese) Português (Portugal)", "pt_pt"),
            Map.entry("(Cantabrian) Cántabru/Montañés (Cantabria)", "qcb_es"),
            Map.entry("(Indonesian, Pre-reform spelling) Bahasa Indonesia edjaän lama (Indonesia tempo doeloe)", "qid"),
            Map.entry("(Quenya, Elvish from The Lord of the Rings) Quenya (Arda)", "qya_aa"),
            Map.entry("(Romanian) Română (România)", "ro_ro"),
            Map.entry("(Russian, Pre-revolutionary) Русскій дореформенный (Россійская имперія)", "rpr"),
            Map.entry("(Russian) Русский (Россия)", "ru_ru"),
            Map.entry("(Rusyn) Руснацькый (Пудкарпатя, Украина)", "ry_ua"),
            Map.entry("(Yakut) Сахалыы (Cаха Сирэ)", "sah_sah"),
            Map.entry("(Northern Sami) Davvisámegiella (Sápmi)", "se_no"),
            Map.entry("(Slovak) Slovenčina (Slovensko)", "sk_sk"),
            Map.entry("(Slovenian) Slovenščina (Slovenija)", "sl_si"),
            Map.entry("(Somali) Af-Soomaali (Soomaaliya)", "so_so"),
            Map.entry("(Albanian) Shqip (Shqiperia)", "sq_al"),
            Map.entry("(Serbian, Latin) Srpski (Srbija)", "sr_cs"),
            Map.entry("(Serbian, Cyrillic) Српски (Србија)", "sr_sp"),
            Map.entry("(Swedish) Svenska (Sverige)", "sv_se"),
            Map.entry("(Upper Saxon German) Säggs'sch (Saggsn)", "sxu"),
            Map.entry("(Silesian) Ślōnski (Gōrny Ślōnsk)", "szl"),
            Map.entry("(Tamil) தமிழ் (இந்தியா)", "ta_in"),
            Map.entry("(Thai) ไทย (ประเทศไทย)", "th_th"),
            Map.entry("(Tagalog) Tagalog (Pilipinas)", "tl_ph"),
            Map.entry("(Klingon) tlhIngan Hol (tlhIngan wo')", "tlh_aa"),
            Map.entry("(Toki Pona) toki pona (kulupu pona)", "tok"),
            Map.entry("(Turkish) Türkçe (Türkiye)", "tr_tr"),
            Map.entry("(Tatar) Татарча (Татарстан, Рәсәй)", "tt_ru"),
            Map.entry("(Tzotzil) Bats'i k'op (Jobel)", "tzo_mx"),
            Map.entry("(Ukrainian) Українська (Україна)", "uk_ua"),
            Map.entry("(Uzbek) O'zbekcha (O'zbekiston)", "uz_uz"),
            Map.entry("(Valencian) Català (Valencià)", "val_es"),
            Map.entry("(Venetian) Vèneto (Veneto)", "vec_it"),
            Map.entry("(Võro) Võro (Eesti)", "vro"),
            Map.entry("(Vietnamese) Tiếng Việt (Việt Nam)", "vi_vn"),
            Map.entry("(Viossa) Viossa (Vilant)", "vp_vl"),
            Map.entry("(Yiddish) ייִדיש (אשכנזיש יידן)", "yi_de"),
            Map.entry("(Yoruba) Yorùbá (Nàìjíríà)", "yo_ng"),
            Map.entry("(Chinese Simplified, Mainland/Mandarin) 简体中文 (中国大陆)", "zh_cn"),
            Map.entry("(Chinese Traditional, Hong Kong SAR) 繁體中文 (香港特別行政區)", "zh_hk"),
            Map.entry("(Chinese Traditional, Taiwan/Mandarin) 繁體中文 (台灣)", "zh_tw"),
            Map.entry("(Malay, Jawi script) بهاس ملايو (مليسيا)", "zlm_arab")
    );


    public static List<Map.Entry<String, String>> get(String query) {
        if (query == null || query.isBlank()) return List.of();
        final String cleanQuery = normalize(query);
        return VALUES.entrySet().stream().filter(entry ->
                Util.matchesQuery(entry.getValue(), cleanQuery) ||
                        Util.matchesQuery(entry.getKey(), cleanQuery)).toList();
    }

    public static boolean isValidCode(String code) {
        if (code == null || code.isBlank()) return false;
        String trimmed = code.trim();
        return VALUES.values().stream().anyMatch(v -> v.equalsIgnoreCase(trimmed));
    }


}
